### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by AudiWu** [AudiWu/audiwu.com#31]
## Summary
Create a navigation bar

## Todo List
- [ ] Create navbar for desktop
- [ ] Create navbar for tablet
- [ ] Create navbar for phone
