### ISSUE TITLE
Add home page 

### ISSUE THREAD

**Issue by AudiWu** [AudiWu/audiwu.com#53]
## Summary
Create a home page 

## TODO list
- [ ] tell about yourself
- [ ] tell your work experience
- [ ] tell your hobby
- [ ] contact
